#!/usr/bin/env python3
"""
NanoClaw Executor Setup Wizard

Interactive configuration wizard for setting up the QA Swarm Executor.
Generates .env file with validated configuration.

Usage:
    python -m cli.setup
    python cli/setup.py
"""

import os
import sys
from datetime import datetime
from pathlib import Path
from typing import Dict, Optional

from rich.console import Console
from rich.panel import Panel
from rich.table import Table

# Add parent directory to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent))

from cli.connection_testers import (
    test_jira_connection,
    test_jira_project,
    test_shared_volume,
    test_teams_connection,
)
from cli.prompts import (
    ask_test_connections,
    confirm_configuration,
    configure_advanced,
    configure_health_thresholds,
    configure_jira,
    configure_shared_volume,
    configure_teams,
    configure_whatsapp,
    select_services,
    DEFAULTS,
)

console = Console()

# .env template with all variables
ENV_TEMPLATE = """# NanoClaw Executor Configuration
# Generated by setup wizard on {timestamp}
# ---------------------------------------------------------

# Jira Configuration
JIRA_BASE_URL={JIRA_BASE_URL}
JIRA_API_TOKEN={JIRA_API_TOKEN}
JIRA_EMAIL={JIRA_EMAIL}
JIRA_PROJECT_KEY={JIRA_PROJECT_KEY}

# WhatsApp Configuration (optional - for trigger interface)
WHATSAPP_WEBHOOK_URL={WHATSAPP_WEBHOOK_URL}
WHATSAPP_AUTH_TOKEN={WHATSAPP_AUTH_TOKEN}

# Shared Volume Configuration
# Path to Role 1's shared volume
SHARED_VOLUME_PATH={SHARED_VOLUME_PATH}
SHARED_SCRIPTS_DIR=${{SHARED_VOLUME_PATH}}/egress
SHARED_RESULTS_DIR=${{SHARED_VOLUME_PATH}}/results

# Executor Service
EXECUTOR_HOST={EXECUTOR_HOST}
EXECUTOR_PORT={EXECUTOR_PORT}
EXECUTOR_LOG_LEVEL={EXECUTOR_LOG_LEVEL}

# Monitor Service
MONITOR_HOST={MONITOR_HOST}
MONITOR_PORT={MONITOR_PORT}
MONITOR_LOG_LEVEL={MONITOR_LOG_LEVEL}
MONITOR_SAMPLE_INTERVAL_MS={MONITOR_SAMPLE_INTERVAL_MS}

# Jira Integrator Service
JIRA_INTEGRATOR_HOST={JIRA_INTEGRATOR_HOST}
JIRA_INTEGRATOR_PORT={JIRA_INTEGRATOR_PORT}
JIRA_INTEGRATOR_LOG_LEVEL={JIRA_INTEGRATOR_LOG_LEVEL}

# Health Thresholds
HEALTH_MEMORY_LEAK_THRESHOLD_MB={HEALTH_MEMORY_LEAK_THRESHOLD_MB}
HEALTH_MEMORY_LEAK_WINDOW_SECONDS={HEALTH_MEMORY_LEAK_WINDOW_SECONDS}
HEALTH_CPU_WARNING_PERCENT={HEALTH_CPU_WARNING_PERCENT}
HEALTH_CPU_CRITICAL_PERCENT={HEALTH_CPU_CRITICAL_PERCENT}
HEALTH_CPU_IDLE_WINDOW_SECONDS={HEALTH_CPU_IDLE_WINDOW_SECONDS}

# Execution Settings
EXECUTION_TIMEOUT_SECONDS={EXECUTION_TIMEOUT_SECONDS}
BROWSER_HEADLESS={BROWSER_HEADLESS}
BROWSER_SLOW_MO_MS=0

# Docker Configuration
DOCKER_NETWORK={DOCKER_NETWORK}
EXECUTOR_CONTAINER_NAME=nanoclaw_executor
MONITOR_CONTAINER_NAME=nanoclaw_monitor
JIRA_CONTAINER_NAME=nanoclaw_jira

# Playwright Configuration
PLAYWRIGHT_TRACE_ON=true
PLAYWRIGHT_TRACE_RETAIN_ON_FAILURE=true
PLAYWRIGHT_SCREENSHOT_ON_FAILURE_ONLY=true

# Teams Configuration
TEAMS_APP_ID={TEAMS_APP_ID}
TEAMS_APP_PASSWORD={TEAMS_APP_PASSWORD}
TEAMS_SERVICE_URL={TEAMS_SERVICE_URL}
TEAMS_PORT={TEAMS_PORT}
"""


def get_default_config() -> Dict[str, str]:
    """Get default configuration values."""
    return {
        "JIRA_BASE_URL": "",
        "JIRA_API_TOKEN": "",
        "JIRA_EMAIL": "",
        "JIRA_PROJECT_KEY": DEFAULTS["JIRA_PROJECT_KEY"],
        "WHATSAPP_WEBHOOK_URL": "",
        "WHATSAPP_AUTH_TOKEN": "",
        "SHARED_VOLUME_PATH": DEFAULTS["SHARED_VOLUME_PATH"],
        "EXECUTOR_HOST": DEFAULTS["EXECUTOR_HOST"],
        "EXECUTOR_PORT": DEFAULTS["EXECUTOR_PORT"],
        "EXECUTOR_LOG_LEVEL": DEFAULTS["EXECUTOR_LOG_LEVEL"],
        "MONITOR_HOST": DEFAULTS["MONITOR_HOST"],
        "MONITOR_PORT": DEFAULTS["MONITOR_PORT"],
        "MONITOR_LOG_LEVEL": DEFAULTS["MONITOR_LOG_LEVEL"],
        "MONITOR_SAMPLE_INTERVAL_MS": DEFAULTS["MONITOR_SAMPLE_INTERVAL_MS"],
        "JIRA_INTEGRATOR_HOST": DEFAULTS["JIRA_INTEGRATOR_HOST"],
        "JIRA_INTEGRATOR_PORT": DEFAULTS["JIRA_INTEGRATOR_PORT"],
        "JIRA_INTEGRATOR_LOG_LEVEL": "INFO",
        "HEALTH_MEMORY_LEAK_THRESHOLD_MB": DEFAULTS["HEALTH_MEMORY_LEAK_THRESHOLD_MB"],
        "HEALTH_MEMORY_LEAK_WINDOW_SECONDS": DEFAULTS["HEALTH_MEMORY_LEAK_WINDOW_SECONDS"],
        "HEALTH_CPU_WARNING_PERCENT": DEFAULTS["HEALTH_CPU_WARNING_PERCENT"],
        "HEALTH_CPU_CRITICAL_PERCENT": DEFAULTS["HEALTH_CPU_CRITICAL_PERCENT"],
        "HEALTH_CPU_IDLE_WINDOW_SECONDS": DEFAULTS["HEALTH_CPU_IDLE_WINDOW_SECONDS"],
        "EXECUTION_TIMEOUT_SECONDS": DEFAULTS["EXECUTION_TIMEOUT_SECONDS"],
        "BROWSER_HEADLESS": DEFAULTS["BROWSER_HEADLESS"],
        "DOCKER_NETWORK": DEFAULTS["DOCKER_NETWORK"],
        "TEAMS_APP_ID": "",
        "TEAMS_APP_PASSWORD": "",
        "TEAMS_SERVICE_URL": "http://localhost:8004",
        "TEAMS_PORT": DEFAULTS["TEAMS_PORT"],
    }


def load_existing_config(env_path: Path) -> Optional[Dict[str, str]]:
    """Load existing .env file if it exists."""
    if not env_path.exists():
        return None

    config = {}
    try:
        with open(env_path, "r") as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    key, _, value = line.partition("=")
                    config[key.strip()] = value.strip()
        return config
    except Exception as e:
        console.print(f"[yellow]Warning: Could not read existing .env: {e}[/yellow]")
        return None


def backup_env_file(env_path: Path) -> Optional[Path]:
    """Create backup of existing .env file."""
    if not env_path.exists():
        return None

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    backup_path = env_path.with_suffix(f".env.backup.{timestamp}")

    try:
        import shutil
        shutil.copy2(env_path, backup_path)
        return backup_path
    except Exception as e:
        console.print(f"[yellow]Warning: Could not backup .env: {e}[/yellow]")
        return None


def write_env_file(config: Dict[str, str], env_path: Path) -> bool:
    """Write configuration to .env file."""
    try:
        content = ENV_TEMPLATE.format(
            timestamp=datetime.now().isoformat(),
            **config
        )

        with open(env_path, "w") as f:
            f.write(content)

        return True
    except Exception as e:
        console.print(f"[red]Error writing .env file: {e}[/red]")
        return False


def test_all_connections(config: Dict[str, str], services: list) -> Dict[str, bool]:
    """Test all configured connections."""
    console.print("\n[bold]Testing Connections...[/bold]\n")

    results = {}

    # Test Jira
    if "jira" in services:
        console.print("[cyan]Testing Jira Connection:[/cyan]")
        success, error = test_jira_connection(
            config.get("JIRA_BASE_URL", ""),
            config.get("JIRA_EMAIL", ""),
            config.get("JIRA_API_TOKEN", ""),
        )
        results["jira"] = success

        if success:
            # Also test project access
            success, error = test_jira_project(
                config.get("JIRA_BASE_URL", ""),
                config.get("JIRA_EMAIL", ""),
                config.get("JIRA_API_TOKEN", ""),
                config.get("JIRA_PROJECT_KEY", ""),
            )
            results["jira_project"] = success

            if not success:
                console.print(f"  [yellow]⚠[/yellow] {error}")
        else:
            console.print(f"  [red]✗[/red] {error}")

    # Test Teams
    if "teams" in services:
        console.print("\n[cyan]Testing Teams Credentials:[/cyan]")
        success, error = test_teams_connection(
            config.get("TEAMS_APP_ID", ""),
            config.get("TEAMS_APP_PASSWORD", ""),
        )
        results["teams"] = success

        if not success:
            console.print(f"  [red]✗[/red] {error}")

    # Test shared volume
    console.print("\n[cyan]Testing Shared Volume:[/cyan]")
    success, error = test_shared_volume(config.get("SHARED_VOLUME_PATH", ""))
    results["volume"] = success

    if not success:
        console.print(f"  [red]✗[/red] {error}")

    return results


def show_completion_summary(config: Dict[str, str], env_path: Path, test_results: Dict[str, bool]):
    """Show completion summary with next steps."""
    console.print()

    # Create summary table
    table = Table(show_header=False, box=None)
    table.add_column("Item", style="green")
    table.add_column("Status")

    table.add_row("✓", f".env file created at: {env_path}")

    # Service status
    services_configured = []
    if config.get("JIRA_BASE_URL"):
        services_configured.append("Jira Integration")
    if config.get("TEAMS_APP_ID"):
        services_configured.append("MS Teams Bot")
    if config.get("WHATSAPP_WEBHOOK_URL"):
        services_configured.append("WhatsApp Notifications")

    if services_configured:
        table.add_row("✓", "Services configured: " + ", ".join(services_configured))

    # Connection test results
    if test_results:
        all_passed = all(test_results.values())
        if all_passed:
            table.add_row("✓", "All connection tests passed")
        else:
            failed = [k for k, v in test_results.items() if not v]
            table.add_row("⚠", f"Some tests failed: {', '.join(failed)}")

    console.print(Panel(table, title="[bold green]Configuration Complete![/bold green]", border_style="green"))

    # Next steps
    console.print("\n[bold]Next Steps:[/bold]")
    console.print("  1. Review your .env file:")
    console.print(f"     [dim]cat {env_path}[/dim]")
    console.print()
    console.print("  2. Start services:")
    console.print("     [dim]cd docker && docker-compose up -d[/dim]")
    console.print()
    console.print("  3. Verify services are running:")
    console.print("     [dim]curl http://localhost:8001/health[/dim]")
    console.print()


def run_wizard():
    """Run the interactive setup wizard."""
    # Header
    console.print(Panel.fit(
        "[bold cyan]NanoClaw Executor Setup Wizard[/bold cyan]\n"
        "[dim]Interactive configuration for QA Swarm Executor[/dim]",
        border_style="cyan",
    ))

    # Determine .env path
    project_root = Path(__file__).parent.parent
    env_path = project_root / ".env"

    # Check for existing config
    existing_config = load_existing_config(env_path)
    if existing_config:
        console.print(f"\n[yellow]Found existing configuration at {env_path}[/yellow]")
        use_existing = questionary.confirm(
            "Load existing configuration as defaults?",
            default=True,
        ).ask()

        if use_existing:
            config = get_default_config()
            config.update({k: v for k, v in existing_config.items() if v})
        else:
            config = get_default_config()
    else:
        config = get_default_config()

    # Import questionary here to avoid import errors
    import questionary

    # Select services to configure
    services = select_services()

    if not services:
        console.print("[yellow]No services selected. Exiting.[/yellow]")
        return 1

    # Configure each selected service
    if "jira" in services:
        jira_config = configure_jira()
        config.update(jira_config)

    if "teams" in services:
        teams_config = configure_teams()
        config.update(teams_config)

    if "whatsapp" in services:
        whatsapp_config = configure_whatsapp()
        config.update(whatsapp_config)

    if "health" in services:
        health_config = configure_health_thresholds()
        config.update(health_config)

    if "advanced" in services:
        advanced_config = configure_advanced()
        config.update(advanced_config)

    # Always configure shared volume
    volume_config = configure_shared_volume()
    config.update(volume_config)

    # Show summary and confirm
    if not confirm_configuration(config):
        console.print("[yellow]Configuration cancelled.[/yellow]")
        return 1

    # Test connections if requested
    test_results = {}
    if ask_test_connections():
        test_results = test_all_connections(config, services)

        # Check for failures
        failures = [k for k, v in test_results.items() if not v]
        if failures:
            proceed = questionary.confirm(
                f"Some connection tests failed. Continue anyway?",
                default=True,
            ).ask()

            if not proceed:
                console.print("[yellow]Configuration cancelled.[/yellow]")
                return 1

    # Backup existing .env
    backup_path = backup_env_file(env_path)
    if backup_path:
        console.print(f"\n[dim]Backup created: {backup_path}[/dim]")

    # Write .env file
    if write_env_file(config, env_path):
        show_completion_summary(config, env_path, test_results)
        return 0
    else:
        return 1


def main():
    """Main entry point."""
    try:
        import questionary
    except ImportError:
        console.print("[red]Error: questionary not installed.[/red]")
        console.print("Install with: pip install -r requirements-cli.txt")
        return 1

    try:
        return run_wizard()
    except KeyboardInterrupt:
        console.print("\n[yellow]Setup cancelled by user.[/yellow]")
        return 1
    except Exception as e:
        console.print(f"\n[red]Error: {e}[/red]")
        import traceback
        traceback.print_exc()
        return 1


if __name__ == "__main__":
    sys.exit(main())
